
version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"
  backup:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgresql:
        condition: service_started
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=bn_keycloak
      - POSTGRES_DB=bitnami_keycloak
      - POSTGRES_PASSWORD=
      - DAILY_BACKUPS_RETAIN_COUNT=2
      - MONTHLY_BACKUPS_RETAIN_COUNT=1
      - YEARLY_BACKUPS_RETAIN_COUNT=1
      - BACKUP_DIR=/backups
    volumes:
      - './backups:/backups'

volumes:
  postgresql_data:
    driver: local
    